### ISSUE TITLE
ArgumentNullException occurred related to NodeList.

### ISSUE THREAD

**Issue by rasimcekic** [Wouterdek/NodeNetwork#84]
Thank you for sharing this library.

I use [AvalonDock](https://github.com/Dirkster99/AvalonDock) and your library in my project. When the program is first opened, everything works normally like this.

![image](https://user-images.githubusercontent.com/52342396/90223214-4f577580-de16-11ea-83da-fe832ea6e5b8.png)

When switching from dock mode to float mode,  I am encountering the error. "An unhandled exception of type System.ArgumentNullException occurred in System.Reactive.dll Value cannot be null."

![ezgif-5-26e632fe9074](https://user-images.githubusercontent.com/52342396/90226844-51bcce00-de1c-11ea-884b-8cf17e1a9251.gif)

The code below works when switching to float mode.
`

        public NodesListView()
        {
            InitializeComponent();
           
                ViewModel = new ViewModel();

            //DataContext = ViewModel;
            
            this.WhenActivated(d =>  
            {            
                    this.OneWayBind(ViewModel, vm => vm.ListViewModel, v => v.nodeList.ViewModel).DisposeWith(d);          
            });

        }
    }
`
1-When I comment this.WhenActiveted part, I do not encounter any errors.
2-When I switch Nodelist from tiles to list mode and then switch to avalondock's float mode, I don't have any problems As seen in the picture below.(this.WhenActiveted part is not comment line)

![ezgif-5-10194ca81ace](https://user-images.githubusercontent.com/52342396/90227159-c859cb80-de1c-11ea-8074-6231fa0c9429.gif)

The detail of the error I encountered is below.

- System.ArgumentNullException

  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: element
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Controls.Grid.SetRow(UIElement element, Int32 value)
   at NodeNetwork.Views.NodeOutputView.<SetupBindings>b__24_16(Int32 row)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48
   at System.Reactive.Linq.ObservableImpl.CombineLatest`3._.SecondObserver.OnNext(TSecond value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\CombineLatest.cs:line 184
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\DistinctUntilChanged.cs:line 74
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Where.cs:line 56
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Switch.cs:line 103
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 16
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.LoopRec(IScheduler scheduler) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 123
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.<>c.<Run>b__3_0(IScheduler innerScheduler, _ this) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 55
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\ImmediateScheduler.cs:line 41
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.Run(IEnumerable`1 source, IScheduler scheduler) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 56
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 24
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.TailRecursiveSink`1.Drain() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 167
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 33
   at System.Reactive.Linq.ObservableImpl.Concat`1.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Concat.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Linq.ObservableImpl.Switch`1._.OnNext(IObservable`1 value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Switch.cs:line 59
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Switch.cs:line 103
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 16
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.LoopRec(IScheduler scheduler) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 123
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.<>c.<Run>b__3_0(IScheduler innerScheduler, _ this) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 55
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\ImmediateScheduler.cs:line 41
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.Run(IEnumerable`1 source, IScheduler scheduler) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 56
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\ToObservable.cs:line 24
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.TailRecursiveSink`1.Drain() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 167
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 33
   at System.Reactive.Linq.ObservableImpl.Concat`1.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Concat.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Linq.ObservableImpl.Switch`1._.OnNext(IObservable`1 value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Switch.cs:line 59
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48
   at System.Reactive.Linq.ObservableImpl.ReturnImmediate`1.Run(IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Return.cs:line 64
   at System.Reactive.BasicProducer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 70
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.Switch`1.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Switch.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.Switch`1.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Switch.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Where.cs:line 27
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\DistinctUntilChanged.cs:line 24
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Linq.ObservableImpl.CombineLatest`3._.Run(IObservable`1 first, IObservable`1 second) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\CombineLatest.cs:line 58
   at System.Reactive.Linq.ObservableImpl.CombineLatest`3.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\CombineLatest.cs:line 29
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 128
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 424
   at System.Reactive.Sink`2.Run(IObservable`1 source) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 90
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 22
   at System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 121
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 66
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 107
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 61
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 119
   at System.Reactive.Producer`2.Subscribe(IObserver`1 observer) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 97
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 onNext) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 63
   at NodeNetwork.Views.NodeOutputView.<SetupBindings>b__24_0(CompositeDisposable d)
   at ReactiveUI.ViewForMixins.<>c__DisplayClass9_0.<WhenActivated>b__0() in d:\a\1\s\src\ReactiveUI\Activation\ViewForMixins.cs:line 238
   at ReactiveUI.ViewForMixins.<>c__DisplayClass10_0.<HandleViewActivation>b__0(Boolean activated) in d:\a\1\s\src\ReactiveUI\Activation\ViewForMixins.cs:line 255
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 43
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\DistinctUntilChanged.cs:line 72
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Merge.cs:line 236
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Merge.cs:line 236
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 146
   at ReactiveUI.ActivationForViewFetcher.<>c__DisplayClass1_1.<GetActivationForView>g__Handler|9(Object sender, RoutedEventArgs e) in d:\a\1\s\src\ReactiveUI.WPF\ActivationForViewFetcher.cs:line 40
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

  This exception was originally thrown at this call stack:
    [External Code]

Screen Shot
![image](https://user-images.githubusercontent.com/52342396/90225590-4ec0de00-de1a-11ea-9341-9861bdddf282.png)

What can i do to fix it?

**Comment by Sage-of-Mirrors** [comment]
This appears to be related to an issue I posted, #77. In my case, it's related to nodes have multiple controls on them.

**Comment by Wouterdek** [comment]
Thanks for your bug report. Is this still reproducible in the latest version? If so, could you provide a minimal reproducible example? (preferably a zip file with a project that I can debug)
